config/routes.rb
Rails.application.routes.draw do

  resources :expenditures

  resources :procurements

  resources :dispatches do
    resources :dispatched_items
  end
  resources :inventories

  resources :items

  resources :donors

  resources :sites

  resources :volunteers

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :dispatches
  root 'dashboards#index'

end

app/models/dispatch.rb
class Dispatch < ActiveRecord::Base
  belongs_to :site
  has_many :dispatched_items

  validates_presence_of :name, :dispatch_date, :site

  class << self
    def today
      all.where(dispatch_date: Date.today)
    end

    def archive
      all.order(dispatch_date: :desc)
    end
  end

  def dispatched_at
    dispatch_date
  end
end

app/models/dispatched_item.rb
class DispatchedItem < ActiveRecord::Base
  belongs_to :dispatch
  belongs_to :inventory

  after_create :deduct_from_inventory

  validates_presence_of :amount, :inventory, :dispatch

  def self.expenses
    cash_inventory = Inventory.find_by_inventory_type('fund')
    DispatchedItem.where(inventory: cash_inventory).collect(&:amount).sum
  end

  private
    def deduct_from_inventory
      self.inventory.amount -= amount
      self.inventory.save
    end
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :items

  validates_presence_of :name

  def self.list
    all.select(:id, :name)
  end
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  after_create :deduct_funds

  validates_presence_of :amount, :name

  def self.expenses
    all.collect(&:amount).sum
  end

  private
  def deduct_funds
    cash_inventory = Inventory.find_by_inventory_type('fund')
    cash_inventory.amount -= amount
    cash_inventory.save
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates :name, uniqueness: { scope: :inventory_type }
  def self.types
    all.select(:id, :name)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :donor

  after_create :add_to_inventory

  validates_presence_of :amount, :inventory

  def self.income
    cash_inventory = Inventory.find_by_inventory_type('fund')
    Item.where(inventory: cash_inventory).collect(&:amount).sum
  end

  private
    def add_to_inventory
      self.inventory.amount += amount
      self.inventory.save
    end
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  belongs_to :inventory
  after_create :add_to_inventory, :deduct_funds

  validates_presence_of :amount, :inventory, :funds_used

  def self.expenses
    all.collect(&:funds_used).sum
  end

  private
    def deduct_funds
      cash_inventory = Inventory.find_by_inventory_type('fund')
      cash_inventory.amount -= funds_used
      cash_inventory.save
    end

    def add_to_inventory
      self.inventory.amount += amount
      self.inventory.save
    end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :dispatches
  has_many :requests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         #:registerable,
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @donors = Donor.all
    respond_with(@donors)
  end

  def show
    respond_with(@donor)
  end

  def new
    @donor = Donor.new
    respond_with(@donor)
  end

  def edit
  end

  def create
    @donor = Donor.new(donor_params)
    @donor.save
    redirect_to donors_path
  end

  def update
    @donor.update(donor_params)
    respond_with(@donor)
  end

  def destroy
    @donor.destroy
    respond_with(@donor)
  end

  private
    def set_donor
      @donor = Donor.find(params[:id])
    end

    def donor_params
      params.require(:donor).permit(:name, :address, :phone_number, :email)
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @inventories = Inventory.all
    respond_with(@inventories)
  end

  def show
    respond_with(@inventory)
  end

  def new
    @inventory = Inventory.new
    respond_with(@inventory)
  end

  def edit
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.save
    respond_with(@inventory)
  end

  def update
    @inventory.update(inventory_params)
    respond_with(@inventory)
  end

  def destroy
    @inventory.destroy
    respond_with(@inventory)
  end

  private
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    def inventory_params
      params.require(:inventory).permit(:inventory_type, :name, :amount, :unit)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to items_path
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :amount, :units, :type, :submit_date, :donor_id, :inventory_id)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sites = Site.all
    respond_with(@sites)
  end

  def show
    respond_with(@site)
  end

  def new
    @site = Site.new
    respond_with(@site)
  end

  def edit
  end

  def create
    @site = Site.new(site_params)
    @site.save
    respond_with(@site)
  end

  def update
    @site.update(site_params)
    respond_with(@site)
  end

  def destroy
    @site.destroy
    respond_with(@site)
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:name, :district, :vdc, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dispatch_helper.rb
module DispatchHelper
  def dispatch_status
    [
      "Ready to Dispatch",
      "Dispatched",
      "Delivered"
    ]
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/procurements_helper.rb
module ProcurementsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @inventory.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h4>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :inventory_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :inventory_type, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :amount, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :unit, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/inventories/_inventory_list.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Amount</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @inventories) do |inventory| %>
            <td><%= inventory.name.humanize %></td>
            <td><%= inventory.inventory_type.humanize %></td>
            <td><%= inventory.amount %> <%= inventory.unit %></td>
            <!-- <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      <% end %>
    </tbody>
  </table>
</div>

app/views/inventories/edit.html.erb
<div class="page-header">
  <%= link_to inventories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @inventory, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing inventory</h1>
</div>

<%= render 'form' %>

app/views/inventories/index.slim
<div class="page-header">
  = link_to new_inventory_path, :class => 'btn btn-primary' do
    <span class="glyphicon glyphicon-plus"></span>
    New Inventory
  end
  <h1>Listing inventories</h1>
</div>
= render 'inventory_list'

app/views/inventories/new.html.erb
<div class="page-header">
  <%= link_to inventories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New inventory</h1>
</div>

<%= render 'form' %>

app/views/inventories/show.html.erb
<div class="page-header">
  <%= link_to inventories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_inventory_path(@inventory), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show inventory</h1>
</div>

<dl class="dl-horizontal">
  <dt>Inventory type:</dt>
  <dd><%= @inventory.inventory_type %></dd>

  <dt>Name:</dt>
  <dd><%= @inventory.name %></dd>

  <dt>Amount:</dt>
  <dd><%= @inventory.amount %></dd>

  <dt>Unit:</dt>
  <dd><%= @inventory.unit %></dd>

</dl>