config/routes.rb
Rails.application.routes.draw do

  resources :expenditures

  resources :procurements

  resources :dispatches do
    resources :dispatched_items
  end
  resources :inventories

  resources :items

  resources :donors

  resources :sites

  resources :volunteers

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :dispatches
  root 'dashboards#index'

end

app/models/dispatch.rb
class Dispatch < ActiveRecord::Base
  belongs_to :site
  has_many :dispatched_items

  validates_presence_of :name, :dispatch_date, :site

  class << self
    def today
      all.where(dispatch_date: Date.today)
    end

    def archive
      all.order(dispatch_date: :desc)
    end
  end

  def dispatched_at
    dispatch_date
  end
end

app/models/dispatched_item.rb
class DispatchedItem < ActiveRecord::Base
  belongs_to :dispatch
  belongs_to :inventory

  after_create :deduct_from_inventory

  validates_presence_of :amount, :inventory, :dispatch

  def self.expenses
    cash_inventory = Inventory.find_by_inventory_type('fund')
    DispatchedItem.where(inventory: cash_inventory).collect(&:amount).sum
  end

  private
    def deduct_from_inventory
      self.inventory.amount -= amount
      self.inventory.save
    end
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :items

  validates_presence_of :name

  def self.list
    all.select(:id, :name)
  end
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  after_create :deduct_funds

  validates_presence_of :amount, :name

  def self.expenses
    all.collect(&:amount).sum
  end

  private
  def deduct_funds
    cash_inventory = Inventory.find_by_inventory_type('fund')
    cash_inventory.amount -= amount
    cash_inventory.save
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  validates :name, uniqueness: { scope: :inventory_type }
  def self.types
    all.select(:id, :name)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :donor

  after_create :add_to_inventory

  validates_presence_of :amount, :inventory

  def self.income
    cash_inventory = Inventory.find_by_inventory_type('fund')
    Item.where(inventory: cash_inventory).collect(&:amount).sum
  end

  private
    def add_to_inventory
      self.inventory.amount += amount
      self.inventory.save
    end
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  belongs_to :inventory
  after_create :add_to_inventory, :deduct_funds

  validates_presence_of :amount, :inventory, :funds_used

  def self.expenses
    all.collect(&:funds_used).sum
  end

  private
    def deduct_funds
      cash_inventory = Inventory.find_by_inventory_type('fund')
      cash_inventory.amount -= funds_used
      cash_inventory.save
    end

    def add_to_inventory
      self.inventory.amount += amount
      self.inventory.save
    end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :dispatches
  has_many :requests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         #:registerable,
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
end

app/controllers/dispatched_items_controller.rb
class DispatchedItemsController < ApplicationController
  before_action :set_dispatched_item, only: [:show, :edit, :update, :destroy]
  before_action :set_dispatch
  respond_to :html

  def index
    @dispatched_items = DispatchedItem.all
    respond_with(@dispatch, @dispatched_item)
  end

  def show
    respond_with(@dispatch, @dispatched_item)
  end

  def new
    @dispatched_item = DispatchedItem.new
    respond_with(@dispatch, @dispatched_item)
  end

  def edit
  end

  def create
    @dispatched_item = DispatchedItem.new(dispatched_item_params)
    @dispatched_item.dispatch_id = params['dispatch_id']
    @dispatched_item.save
    redirect_to dispatch_dispatched_items_path(@dispatch)
  end

  def update
    stock_adjust = @dispatched_item.amount - dispatched_item_params['amount'].to_i
    @dispatched_item.update(dispatched_item_params)
    inventory = @dispatched_item.inventory
    inventory.update_attributes(amount: inventory.amount + stock_adjust)
    redirect_to dispatch_dispatched_items_path(@dispatch)
  end

  def destroy
    @dispatched_item.destroy
    redirect_to dispatch_dispatched_items_path(@dispatch)
  end

  private
    def set_dispatched_item
      @dispatched_item = DispatchedItem.find(params[:id])
    end

    def set_dispatch
      @dispatch = Dispatch.find params['dispatch_id']
    end

    def dispatched_item_params
      params.require(:dispatched_item).permit(:dispatch_id, :inventory_id, :amount, :unit)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to items_path
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :amount, :units, :type, :submit_date, :donor_id, :inventory_id)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sites = Site.all
    respond_with(@sites)
  end

  def show
    respond_with(@site)
  end

  def new
    @site = Site.new
    respond_with(@site)
  end

  def edit
  end

  def create
    @site = Site.new(site_params)
    @site.save
    respond_with(@site)
  end

  def update
    @site.update(site_params)
    respond_with(@site)
  end

  def destroy
    @site.destroy
    respond_with(@site)
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:name, :district, :vdc, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dispatch_helper.rb
module DispatchHelper
  def dispatch_status
    [
      "Ready to Dispatch",
      "Dispatched",
      "Delivered"
    ]
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/procurements_helper.rb
module ProcurementsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/dispatched_items/_dispatched_items.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Dispatch</th>
            <th>Inventory</th>
            <th>Amount</th>
            <th>Unit</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @dispatch.dispatched_items) do |dispatched_item| %>
            <td><%= dispatched_item.dispatch.name %></td>
            <td><%= dispatched_item.inventory.name %></td>
            <td><%= dispatched_item.amount %></td>
            <td><%= dispatched_item.inventory.unit %></td>
            <td><%= link_to 'Show', dispatch_dispatched_item_path(@dispatch, dispatched_item) %></td>
        <td><%= link_to 'Edit', edit_dispatch_dispatched_item_path(@dispatch, dispatched_item) %></td>
        <td><%= link_to 'Destroy', dispatch_dispatched_item_path(@dispatch, dispatched_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dispatched_items/_form.html.erb
<%= form_for([@dispatch, @dispatched_item], :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @dispatched_item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@dispatched_item.errors.count, "error") %> prohibited this dispatched_item from being saved:</h4>

      <ul>
      <% @dispatched_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= label_tag 'inventory_type', 'Inventory Type', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= select_tag :inventory_parent_type, options_for_select(Inventory.all.pluck(:inventory_type).uniq), :class => "form-control" %>
      </div>
  </div>
  <div class="form-group">
    <%= select_tag :all_inventory_types, options_for_select(Inventory.all.map{ |i| [i.name.humanize, i.id, { 'data-unit' => i.unit, 'data-type' => i.inventory_type }] }), :class => "form-control hidden" %>

    <%= f.label :inventory, 'Inventory Item', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10 inventory-type-select">
      <%= f.select :inventory_id, options_for_select(Inventory.all.map{ |i| [i.name.humanize, i.id, { 'data-unit' => i.unit, 'data-type' => i.inventory_type }] }), {}, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :amount, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :amount, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :unit, :class => "form-control unit-input", :disabled => true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/dispatched_items/edit.html.erb
<div class="page-header">
  <%= link_to dispatch_dispatched_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to [@dispatch, @dispatched_item], :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing dispatched_item</h1>
</div>

<%= render 'form' %>

app/views/dispatched_items/index.html.erb
<div class="page-header">
  <%= link_to new_dispatch_dispatched_item_path(@dispatch), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Dispatched item
  <% end %>
  <h1>Listing dispatched_items for <%= @dispatch.site.try(:name) %></h1>
</div>

<%= render :partial => "dispatched_items", :locals => {:dispatch => @dispatch, :dispatched_items=>@dispatched_items} %>

app/views/dispatched_items/new.html.erb
<div class="page-header">
  <%= link_to dispatch_dispatched_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New dispatched_item</h1>
</div>

<%= render 'form' %>

app/views/dispatched_items/show.html.erb
<div class="page-header">
  <%= link_to dispatch_dispatched_items_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_dispatch_dispatched_item_path(@dispatch, @dispatched_item), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show dispatched_item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Dispatch:</dt>
  <dd><%= @dispatched_item.dispatch.name %></dd>

  <dt>Inventory:</dt>
  <dd><%= @dispatched_item.inventory.try(:name) %></dd>

  <dt>Amount:</dt>
  <dd><%= @dispatched_item.amount %></dd>

  <dt>Unit:</dt>
  <dd><%= @dispatched_item.unit %></dd>

</dl>